name:                memcached-replicator
version:             0.1.0.0
github:              "restaumatic/memcached-replicator"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

description:         memcached-replicator

dependencies:
- base >= 4.7 && < 5
- network
- memcache
- text
- uri-encode
- random
- bytestring
- async
- vector
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

# See https://ro-che.info/articles/2015-10-26-static-linking-ghc
- -optl-static
- -optl-pthread

executables:
  memcached-replicator:
    main:                Main.hs
    source-dirs:         app
