name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '8.6.3'
        enable-stack: true
        stack-version: 'latest'
    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Build dependencies
      run: |
        stack --no-terminal build --test --only-dependencies
    - name: Build
      run: |
        mkdir dist
        stack --no-terminal build --test --no-run-tests --copy-bins --local-bin-path dist
    - name: Test
      run: stack --no-terminal build --test
    - name: Zip
      run: |
        cd dist
        tar czvf memcached-copy-linux.tar.gz memcached-copy
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: memcached-copy-linux.tar.gz
        path: |
          dist/memcached-copy-linux.tar.gz
